### ISSUE TITLE
Cant import PyV8 after install

### ISSUE THREAD

**Issue by GoogleCodeExporter** [charx0r/pyv8#112]
```
What steps will reproduce the problem?
1. svn down V8 and PyV8 to ~/src
2. cd ~/src/v8 && make x64
3. cd ~/src/pyv8-read-only 
4. sudo V8_HOME=$HOME/src/v8 python setup.py install
5. 

What is the expected output? What do you see instead?
I dont really know expected output, I get this instead:
➜  pyv8-read-only  python -m PyV8                                   
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/simon/src/pyv8-read-only/PyV8.py", line 17, in <module>
    import _PyV8
ImportError: 
/usr/local/lib/python2.7/dist-packages/PyV8-1.0-py2.7-linux-x86_64.egg/_PyV8.so:
 undefined symbol: 
_ZN2v88internal10AstVisitor17VisitDeclarationsEPNS0_8ZoneListIPNS0_11Declaration
EEE


What version of the product are you using? On what operating system?
*Kubuntu 11.10, 3.0.0-12-generic #20-Ubuntu SMP Fri Oct 7 14:56:25 UTC 2011 
x86_64 x86_64 x86_64 GNU/Linux
*Python 2.7.2+ (default, Oct  4 2011, 20:06:09) 
*svn checkout http://pyv8.googlecode.com/svn/trunk/ pyv8-read-only
*svn checkout http://v8.googlecode.com/svn/trunk/ v8

```

Original issue reported on code.google.com by `si...@editd.com` on 21 Nov 2011 at 1:03

**Comment by GoogleCodeExporter** [comment]
```
Compiled V8 with make native instead of make x64.
Removed old PyV8 installation with easy_install and did a install again.
Same problem.
```

Original comment by `si...@editd.com` on 21 Nov 2011 at 1:22

**Comment by GoogleCodeExporter** [comment]
```
Sorry, but I can't reproduce your issue on a Ubuntu 11.10 system, could you try 
the private build in the attachment, which built with Python 2.7 and Boost 1.42

$uname -a
Linux Ubuntu64 3.0.0-13-generic #22-Ubuntu SMP Wed Nov 2 13:27:26 UTC 2011 
x86_64 x86_64 x86_64 GNU/Linux

$python
Python 2.7.2+ (default, Oct  4 2011, 20:06:09) 

$ ldd _PyV8.so 
    linux-vdso.so.1 =>  (0x00007fff4b16c000)
    libboost_python-py27.so.1.42.0 => /usr/lib/libboost_python-py27.so.1.42.0 (0x00007f2d0cb8e000)
    libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f2d0c887000)
    libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f2d0c602000)
    libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f2d0c3ec000)
    libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f2d0c1cf000)
    libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f2d0be2f000)
    libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f2d0bc2c000)
    libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f2d0ba28000)
    librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f2d0b81f000)
    /lib64/ld-linux-x86-64.so.2 (0x00007f2d0d5f4000)
```

Original comment by `flier...@gmail.com` on 1 Dec 2011 at 6:18
- Added labels: **OpSys-Linux**

Attachments:
- [pyv8.tar.gz](https://storage.googleapis.com/google-code-attachments/pyv8/issue-112/comment-2/pyv8.tar.gz)

**Comment by GoogleCodeExporter** [comment]
```
btw: please don't build v8 by manual, just set the V8_HOME env variable point 
to it, and use PyV8 setup.py, which will patch v8 SConstruct before use it.

Thanks
```

Original comment by `flier...@gmail.com` on 1 Dec 2011 at 6:20
- Changed state: **Invalid**

**Comment by GoogleCodeExporter** [comment]
```
Thank you!
This resolved my issue.
```

Original comment by `si...@editd.com` on 1 Dec 2011 at 3:21
