### ISSUE TITLE
AttributeError: 'Boost.Python.StaticProperty' object attribute '__doc__' is read-only 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [charx0r/pyv8#12]
```
What steps will reproduce the problem?
1. Install PyV8-0.7.1.win32-py2.6 under Windows 7
2. Open the Python interpreter
3. import PyV8

What is the expected output? 
No error.

What do you see instead?
ActivePython 2.6.3.7 (ActiveState Software Inc.) based on
Python 2.6.3 (r263:75183, Oct  5 2009, 14:41:55) [MSC v.1500 32 bit 
(Intel)] on
win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import PyV8
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Languages\Python26\lib\site-packages\PyV8.py", line 8, in 
<module>
    import _PyV8
AttributeError: 'Boost.Python.StaticProperty' object attribute '__doc__' is 
read-only

What version of the product are you using? On what operating system?
PyV8-0.7.1.win32-py2.6 under Win7 RC.

Please provide any additional information below.
The same version of PyV8 works fine under WinXP SP3.

```

Original issue reported on code.google.com by `wuwe...@gmail.com` on 10 Dec 2009 at 8:02

**Comment by GoogleCodeExporter** [comment]
```
It is very strange, because I also using Win7 with Python 2.6.

After google the keyword, I found somebody has similar issue on ubuntu karmic, 
I will 
try his solution later.

http://aspn.activestate.com/ASPN/Mail/Message/cpp-sig/3746196
```

Original comment by `flier...@gmail.com` on 10 Dec 2009 at 10:40
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
I have submitted the code that use add_property instead of def_readonly, could 
you help 
us to verify the issue on your system? Because my Win7 with Python 2.6.4.8 
can't reproduce 
the issue :(

Please check out the code from SVN after revision #173, and compile it with V8 
2.0.x, or use 
the private build in attachment for your test.

Thanks
```

Original comment by `flier...@gmail.com` on 17 Dec 2009 at 11:27
- Changed state: **Fixed**

Attachments:
- [PyV8.zip](https://storage.googleapis.com/google-code-attachments/pyv8/issue-12/comment-2/PyV8.zip)

**Comment by GoogleCodeExporter** [comment]
```
Issue 14 has been merged into this issue.
```

Original comment by `flier...@gmail.com` on 20 Dec 2009 at 3:16

**Comment by GoogleCodeExporter** [comment]
```
i've the same env: Win 7 x86 32-bit with the attached private build it works 
just 
fine, thanks
```

Original comment by `dimo...@gmail.com` on 24 Dec 2009 at 6:32

**Comment by GoogleCodeExporter** [comment]
```
Thanks, dimonio, it will be merged in the next version.
```

Original comment by `flier...@gmail.com` on 25 Dec 2009 at 1:51

**Comment by GoogleCodeExporter** [comment]
```
For those who still get this on Karmic with latest SVN, you need a newer boost
version: do sudo add-apt-repository ppa:ajmitch/ppa and update the
libboost-python-dev package.
```

Original comment by `sciyoshi` on 29 Dec 2009 at 8:00
