### ISSUE TITLE
Problem with installation on Mac OS X using pip

### ISSUE THREAD

**Issue by GoogleCodeExporter** [charx0r/pyv8#156]
```
What steps will reproduce the problem?
1. pip install PyV8

What is the expected output? What do you see instead?
Success installation

What version of the product are you using? On what operating system?
> pip --version
pip 1.2.1 from /usr/local/lib/python2.7/site-packages/pip-1.2.1-py2.7.egg 
(python 2.7)

> python --version
Python 2.7.3

> v8
V8 version 3.15.11 [sample shell]

> cc -v 
Apple LLVM version 4.2 (clang-425.0.24) (based on LLVM 3.2svn)
Target: x86_64-apple-darwin12.2.0
Thread model: posix

Boost: 1.52

Please provide any additional information below.

Error: https://gist.github.com/4674971
Boost and v8 are installed by Home Brew

```

Original issue reported on code.google.com by `maia.j...@gmail.com` on 30 Jan 2013 at 5:44

**Comment by GoogleCodeExporter** [comment]
Original comment by `flier...@gmail.com` on 1 Feb 2013 at 1:56
- Changed state: **Accepted**
- Added labels: **OpSys-All**, **Type-Enhancement**
- Removed labels: **Type-Defect**

**Comment by GoogleCodeExporter** [comment]
```
Please verify it with SVN trunk code after r476, thanks

$sudo pip install -v PyV8
```

Original comment by `flier...@gmail.com` on 2 Feb 2013 at 12:50
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
I got it https://gist.github.com/4697869
I try build from source and test with example on main page do not work.

Maybe I did something wrong, if possible guide me with some steps to try detect 
the problem will be useful.

> python
imPython 2.7.3 (default, Jan 29 2013, 22:12:09) 
[GCC 4.2.1 Compatible Apple LLVM 4.2 (clang-425.0.24)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import PyV8
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/PyV8-1.0_dev-py2.7-macosx-10.8-x86_64.egg/PyV8.py", line 19, in <module>
    import _PyV8
ImportError: 
dlopen(/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/l
ib/python2.7/site-packages/PyV8-1.0_dev-py2.7-macosx-10.8-x86_64.egg/_PyV8.so, 
2): Symbol not found: __ZTIN2v88internal10AstVisitorE
  Referenced from: /usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/PyV8-1.0_dev-py2.7-macosx-10.8-x86_64.egg/_PyV8.so
  Expected in: flat namespace
 in /usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/PyV8-1.0_dev-py2.7-macosx-10.8-x86_64.egg/_PyV8.so
>>> 
```

Original comment by `maia.j...@gmail.com` on 2 Feb 2013 at 4:23

**Comment by GoogleCodeExporter** [comment]
```
It seems you linked PyV8 with wrong V8 library, please remove the PIP cache and 
make a clean build again, thanks
```

Original comment by `flier...@gmail.com` on 7 Feb 2013 at 3:21

**Comment by GoogleCodeExporter** [comment]
```
> pip install PyV8
...
Successfully installed PyV8
Cleaning up...

thks!
```

Original comment by `maia.j...@gmail.com` on 7 Feb 2013 at 3:40

**Comment by GoogleCodeExporter** [comment]
```
I have this same issue on OS X 10.8.3. I deleted the pip build cache, tried 
again from scratch, but it didn't work. the only potential error it showed was:

    ld: warning: directory not found for option '-L/opt/local/lib'
    ld: warning: directory not found for option '-L/Users/csaftoiu/work/testenv/build/PyV8/build/v8/out/native/'

Might that be the reason? full transcript attached


```

Original comment by `csaft...@gmail.com` on 12 Jul 2013 at 6:46

Attachments:
- [transcript](https://storage.googleapis.com/google-code-attachments/pyv8/issue-156/comment-6/transcript)

**Comment by GoogleCodeExporter** [comment]
```
Thanks, it's my fault to add a nonexists folder when fix another issue
```

Original comment by `flier...@gmail.com` on 15 Jul 2013 at 4:44

**Comment by GoogleCodeExporter** [comment]
```
Thanks, it's my fault to add a nonexists folder when fix another issue
```

Original comment by `flier...@gmail.com` on 15 Jul 2013 at 4:44

**Comment by GoogleCodeExporter** [comment]
```
I am using Mas OS X 10.10.3 and Pythion 2.7.9
but having trouble installing it as well get the error

Command "/usr/local/opt/python/bin/python2.7 -c "import setuptools, 
tokenize;__file__='/private/tmp/pip-build-wBGnlW/PyV8/setup.py';exec(compile(get
attr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 
'exec'))" install --record /tmp/pip-RjLC_I-record/install-record.txt 
--single-version-externally-managed --compile" failed with error code 1 in 
/private/tmp/pip-build-wBGnlW/PyV8
    Exception information:
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/site-packages/pip/basecommand.py", line 246, in main
        status = self.run(options, args)
      File "/usr/local/lib/python2.7/site-packages/pip/commands/install.py", line 352, in run
        root=options.root_path,
      File "/usr/local/lib/python2.7/site-packages/pip/req/req_set.py", line 693, in install
        **kwargs
      File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 859, in install
        show_stdout=False,
      File "/usr/local/lib/python2.7/site-packages/pip/utils/__init__.py", line 733, in call_subprocess
        % (command_desc, proc.returncode, cwd))
    InstallationError: Command "/usr/local/opt/python/bin/python2.7 -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-wBGnlW/PyV8/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-RjLC_I-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-build-wBGnlW/PyV8


```

Original comment by `mra...@gmail.com` on 22 Apr 2015 at 6:09

**Comment by GoogleCodeExporter** [comment]
```
Specifically wit the error code:
    clang -fno-strict-aliasing -fno-common -dynamic -I/usr/local/include -I/usr/local/opt/sqlite/include -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -DBOOST_PYTHON_STATIC_LIB -Ilib/python/inc -Ilib/boost/inc -Ilib/v8/inc -I/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c src/Exception.cpp -o build/temp.macosx-10.10-x86_64-2.7/src/Exception.o
    In file included from src/Exception.cpp:1:
    src/Exception.h:6:10: fatal error: 'v8.h' file not found
```

Original comment by `mra...@gmail.com` on 22 Apr 2015 at 6:13

**Comment by GoogleCodeExporter** [comment]
```
Specifically wit the error code:
    clang -fno-strict-aliasing -fno-common -dynamic -I/usr/local/include -I/usr/local/opt/sqlite/include -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -DBOOST_PYTHON_STATIC_LIB -Ilib/python/inc -Ilib/boost/inc -Ilib/v8/inc -I/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c src/Exception.cpp -o build/temp.macosx-10.10-x86_64-2.7/src/Exception.o
    In file included from src/Exception.cpp:1:
    src/Exception.h:6:10: fatal error: 'v8.h' file not found
```

Original comment by `mra...@gmail.com` on 22 Apr 2015 at 6:13
