### ISSUE TITLE
run PyV8.py  error [LookupError: unknown encoding] 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [charx0r/pyv8#179]
```
$ python PyV8.py    
EEEEEEE.E.EEEEEEEEEEE.Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/work/local/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/home/work/local/lib/python2.7/threading.py", line 504, in run
    self.__target(*self.__args, **self.__kwargs)
  File "PyV8.py", line 1875, in run
    """)
LookupError: unknown encoding: 

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/work/local/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/home/work/local/lib/python2.7/threading.py", line 504, in run
    self.__target(*self.__args, **self.__kwargs)
  File "PyV8.py", line 1875, in run
    """)
LookupError: unknown encoding: 

FException in thread Thread-3:
Traceback (most recent call last):
  File "/home/work/local/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/home/work/local/lib/python2.7/threading.py", line 504, in run
    self.__target(*self.__args, **self.__kwargs)
  File "PyV8.py", line 1841, in run
    """)
LookupError: unknown encoding: 

```

Original issue reported on code.google.com by `luocan19...@gmail.com` on 5 Jun 2013 at 2:39

**Comment by GoogleCodeExporter** [comment]
```
I can't reproduce your issue, what's your OS, Python and V8 version and 
encoding?

$ python --version
Python 2.7.5

$ uname -a
Darwin Fliers-MacBook-Pro.local 12.4.0 Darwin Kernel Version 12.4.0: Wed May  1 
17:57:12 PDT 2013; root:xnu-2050.24.15~1/RELEASE_X86_64 x86_64

$ svn info ~/Development/v8
Path: /Users/flier/Development/v8
Working Copy Root Path: /Users/flier/Development/v8
URL: http://v8.googlecode.com/svn/trunk
Repository Root: http://v8.googlecode.com/svn
Repository UUID: ce2b1a6d-e550-0410-aec6-3dcde31c8c00
Revision: 15104
Node Kind: directory
Schedule: normal
Last Changed Author: danno@chromium.org
Last Changed Rev: 15100
Last Changed Date: 2013-06-13 06:31:22 +0800 (Thu, 13 Jun 2013)

$ file PyV8.py
PyV8.py: Python script, UTF-8 Unicode text executable


```

Original comment by `flier...@gmail.com` on 13 Jun 2013 at 6:53

**Comment by GoogleCodeExporter** [comment]
Original comment by `flier...@gmail.com` on 10 Jul 2013 at 7:19
- Changed state: **WontFix**
