### ISSUE TITLE
Builds

### ISSUE THREAD

**Issue by GoogleCodeExporter** [charx0r/pyv8#228]
```
Although not a serious issues, I wanted to cite that no builds for any other 
environments but Windows are available. If you go to "All downloads", every 
other download is marked as "deprecated".

Something might be broken.
```

Original issue reported on code.google.com by `myselfasunder@gmail.com` on 1 Mar 2014 at 8:11

**Comment by GoogleCodeExporter** [comment]
```
In fact, most of pyv8 user are working on the SVN trunk build, because V8 
upgrade very frequently.

Any way, I could upload some build for OSX and ubuntu, any other platform that 
you prefer to support?
```

Original comment by `flier...@gmail.com` on 3 Mar 2014 at 2:22
- Changed state: **Accepted**
- Added labels: **OpSys-All**, **Type-Task**
- Removed labels: **Type-Defect**

**Comment by GoogleCodeExporter** [comment]
```
Nope. That'd be perfect.

It personally prefer a checkout, but it raised a red-flag when only the Windows 
downloads were available. It made it seem as if it was non-trivial to get it 
working in any other environment (though usually the opposite is the case).

You don't know why PIP's install is failing in Ubuntu (13.10), do you?

    In file included from src/Exception.h:6:0,

                     from src/Wrapper.h:8,

                     from src/Wrapper.cpp:1:

    /usr/include/v8.h:2437:8: error:   initializing argument 3 of ‘void v8::ObjectTemplate::SetIndexedPropertyHandler(v8::IndexedPropertyGetter, v8::IndexedPropertySetter, v8::IndexedPropertyQuery, v8::IndexedPropertyDeleter, v8::IndexedPropertyEnumerator, v8::Handle<v8::Value>)’ [-fpermissive]

       void SetIndexedPropertyHandler(IndexedPropertyGetter getter,

            ^

    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1


```

Original comment by `myselfasunder@gmail.com` on 3 Mar 2014 at 4:24

**Comment by GoogleCodeExporter** [comment]
```
I get the same compilation error as myselfasunder above, just for the record. 
That's with pip, which.. I'm kind of stuck with using right now.
```

Original comment by `gdude2...@gmail.com` on 8 Jun 2014 at 12:30

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
I am getting same error:

src/Wrapper.h: In member function ‘const boost::python::api::object& 
CJavascriptArray::ArrayIterator::dereference() const’:

src/Wrapper.h:115:66: warning: returning reference to temporary 
[-Wreturn-local-addr]

     reference dereference() const { return m_array->GetItem(m_idx); }

                                                                  ^

x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 
-Wall -Wstrict-prototypes -fPIC -DBOOST_PYTHON_STATIC_LIB -Ilib/python/inc 
-Ilib/boost/inc -Ilib/v8/inc -I/usr/include/python2.7 -c src/Wrapper.cpp -o 
build/temp.linux-x86_64-2.7/src/Wrapper.o

cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for 
C/ObjC but not for C++ [enabled by default]

In file included from src/Wrapper.cpp:1:0:

src/Wrapper.h: In member function ‘const boost::python::api::object& 
CJavascriptArray::ArrayIterator::dereference() const’:

src/Wrapper.h:115:66: warning: returning reference to temporary 
[-Wreturn-local-addr]

     reference dereference() const { return m_array->GetItem(m_idx); }

                                                                  ^

src/Wrapper.cpp: In static member function ‘static v8::Handle<v8::Boolean> 
CPythonObject::IndexedDeleter(uint32_t, const v8::AccessorInfo&)’:

src/Wrapper.cpp:256:25: warning: variable ‘value’ set but not used 
[-Wunused-but-set-variable]

   v8::Handle<v8::Value> value = IndexedGetter(index, info);

                         ^

src/Wrapper.cpp: In static member function ‘static void 
CPythonObject::SetupObjectTemplate(v8::Handle<v8::ObjectTemplate>)’:

src/Wrapper.cpp:311:84: error: invalid conversion from 
‘v8::Handle<v8::Boolean> (*)(v8::Local<v8::String>, const 
v8::AccessorInfo&)’ to ‘v8::NamedPropertyQuery {aka v8::Handle<v8::Integer> 
(*)(v8::Local<v8::String>, const v8::AccessorInfo&)}’ [-fpermissive]

   clazz->SetNamedPropertyHandler(NamedGetter, NamedSetter, NamedQuery, NamedDeleter);

                                                                                    ^

In file included from src/Exception.h:6:0,

                 from src/Wrapper.h:8,

                 from src/Wrapper.cpp:1:

/usr/include/v8.h:2414:8: error:   initializing argument 3 of ‘void 
v8::ObjectTemplate::SetNamedPropertyHandler(v8::NamedPropertyGetter, 
v8::NamedPropertySetter, v8::NamedPropertyQuery, v8::NamedPropertyDeleter, 
v8::NamedPropertyEnumerator, v8::Handle<v8::Value>)’ [-fpermissive]

   void SetNamedPropertyHandler(NamedPropertyGetter getter,

        ^

src/Wrapper.cpp:312:94: error: invalid conversion from 
‘v8::Handle<v8::Boolean> (*)(uint32_t, const v8::AccessorInfo&) {aka 
v8::Handle<v8::Boolean> (*)(unsigned int, const v8::AccessorInfo&)}’ to 
‘v8::IndexedPropertyQuery {aka v8::Handle<v8::Integer> (*)(unsigned int, 
const v8::AccessorInfo&)}’ [-fpermissive]

   clazz->SetIndexedPropertyHandler(IndexedGetter, IndexedSetter, IndexedQuery, IndexedDeleter);

                                                                                              ^

In file included from src/Exception.h:6:0,

                 from src/Wrapper.h:8,

                 from src/Wrapper.cpp:1:

/usr/include/v8.h:2437:8: error:   initializing argument 3 of ‘void 
v8::ObjectTemplate::SetIndexedPropertyHandler(v8::IndexedPropertyGetter, 
v8::IndexedPropertySetter, v8::IndexedPropertyQuery, 
v8::IndexedPropertyDeleter, v8::IndexedPropertyEnumerator, 
v8::Handle<v8::Value>)’ [-fpermissive]

   void SetIndexedPropertyHandler(IndexedPropertyGetter getter,

        ^

error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

----------------------------------------
Cleaning up...
  Removing temporary dir /tmp/pip_build_root...
Command /usr/bin/python -c "import setuptools, 
tokenize;__file__='/tmp/pip_build_root/pyv8/setup.py';exec(compile(getattr(token
ize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" 
install --record /tmp/pip-aNn4Aj-record/install-record.txt 
--single-version-externally-managed --compile failed with error code 1 in 
/tmp/pip_build_root/pyv8
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 283, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1435, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 706, in install
    cwd=self.source_dir, filter_stdout=self._filter_install, show_stdout=False)
  File "/usr/lib/python2.7/dist-packages/pip/util.py", line 697, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command /usr/bin/python -c "import setuptools, 
tokenize;__file__='/tmp/pip_build_root/pyv8/setup.py';exec(compile(getattr(token
ize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" 
install --record /tmp/pip-aNn4Aj-record/install-record.txt 
--single-version-externally-managed --compile failed with error code 1 in 
/tmp/pip_build_root/pyv8

Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.4', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 185, in main
    return command.main(cmd_args)
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 161, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 42: 
ordinal not in range(128)
```

Original comment by `kala...@gmail.com` on 25 Oct 2014 at 5:21

**Comment by GoogleCodeExporter** [comment]
```
on my centos 7, I have the same error reported!
```

Original comment by `sh19871...@gmail.com` on 7 May 2015 at 8:19
