### ISSUE TITLE
error: ‘class v8::internal::Expression’ has no member named ‘context’

### ISSUE THREAD

**Issue by GoogleCodeExporter** [charx0r/pyv8#35]
```
pyv8 doesn't seem to build with V8 "stable edge" r3836, or bleeding edge
(same error):

running build_ext
building '_PyV8' extension
creating build/temp.linux-x86_64-2.7
creating build/temp.linux-x86_64-2.7/src
gcc -pthread -DNDEBUG -O2 -march=core2 -m32 -m32 -fPIC
-DBOOST_PYTHON_STATIC_LIB -DV8_NATIVE_REGEXP -DENABLE_DISASSEMBLER
-DENABLE_LOGGING_AND_PROFILING -DENABLE_DEBUGGER_SUPPORT
-DV8_TARGET_ARCH_IA32 -I/med/builds/v8/include -I/med/builds/v8
-I/med/builds/v8/src
-I/home/sys/deploy/installed/Python-x86/include/python2.7 -c src/AST.cpp -o
build/temp.linux-x86_64-2.7/src/AST.o
In file included from src/AST.cpp:1:
src/AST.h: In member function ‘v8::internal::Expression::Context
CAstExpression::context() const’:
src/AST.h:103: error: ‘class v8::internal::Expression’ has no member named
‘context’
error: command 'gcc' failed with exit status 1


I'm on 64-bit Ubuntu karmic with gcc 4.4.1, and compiling v8, boost-python,
and pyv8 as 32-bit.
```

Original issue reported on code.google.com by `sysno...@gmail.com` on 12 Feb 2010 at 2:13

**Comment by GoogleCodeExporter** [comment]
```
V8 tags/2.0.6.6 builds properly with r231 of pyv8, but I get an import error:

>>> import PyV8
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "PyV8.py", line 8, in <module>
    import _PyV8
ImportError:
/home/sys/deploy/installed/Python-x86/lib/python2.7/site-packages/_PyV8.so: 
undefined
symbol: _ZN7CLocker6ExposeEv

For what it's worth, V8 tags/2.0.6.6 and pyv8 r209 (picked semi-randomly) 
builds and
imports just fine.
```

Original comment by `sysno...@gmail.com` on 12 Feb 2010 at 2:42

**Comment by GoogleCodeExporter** [comment]
```
This was likely first broken by http://code.google.com/p/v8/source/detail?r=3645
```

Original comment by `sysno...@gmail.com` on 12 Feb 2010 at 3:17

**Comment by GoogleCodeExporter** [comment]
```
Also compatible: V8 bleeding_edge@3835 (the latest as of now) and pyv8 r209
```

Original comment by `sysno...@gmail.com` on 12 Feb 2010 at 3:43

**Comment by GoogleCodeExporter** [comment]
```
The root cause is Google just remove a obsoleted v8 internal API, since pyv8 
AST 
depend on it. Please verify it with SVN code after r232.

Thanks
```

Original comment by `flier...@gmail.com` on 12 Feb 2010 at 10:23
- Changed state: **Fixed**
- Added labels: **OpSys-All**

**Comment by GoogleCodeExporter** [comment]
```
Builds fine with r233, thanks a lot.
```

Original comment by `sysno...@gmail.com` on 12 Feb 2010 at 12:32

**Comment by GoogleCodeExporter** [comment]
```
Thanks :)
```

Original comment by `flier...@gmail.com` on 12 Feb 2010 at 2:54
- Changed state: **Verified**
