### ISSUE TITLE
Unable to import, importerror _ZN2v88internal10AstVisitor17VisitDeclarationsEPNS0_8ZoneListIPNS0_11DeclarationEEE

### ISSUE THREAD

**Issue by GoogleCodeExporter** [charx0r/pyv8#78]
```
Installed boost 1.46.1, Installed pyv8 @head which checked out v8 @head.

When I try to import, i get this:

onur@onur-vmdesktop:~/linuxdev/pyv8/build$ python2.6
Python 2.6.5 (r265:79063, Apr 16 2010, 13:09:56) 
[GCC 4.4.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import PyV8
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "PyV8.py", line 17, in <module>
  File "build/bdist.linux-i686/egg/_PyV8.py", line 7, in <module>
  File "build/bdist.linux-i686/egg/_PyV8.py", line 6, in __bootstrap__
ImportError: 
/home/onur/.python-eggs/PyV8-1.0-py2.6-linux-i686.egg-tmp/_PyV8.so: undefined 
symbol: 
_ZN2v88internal10AstVisitor17VisitDeclarationsEPNS0_8ZoneListIPNS0_11Declaration
EEE



```

Original issue reported on code.google.com by `on.cel...@gmail.com` on 18 Mar 2011 at 12:18

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
 also tried the compiled version but it tries to read libboost_python-py26.so instead of [...]py25.so.

Could it be possible to have a compiled PyV8.so with right versions of v8 and 
boost included in the .so?
It is too painful to compile pyv8 because of very high version dependencies of 
v8 and boost and python.
```

Original comment by `on.cel...@gmail.com` on 18 Mar 2011 at 7:27

**Comment by GoogleCodeExporter** [comment]
```
Please use pyv8's setup.py to checkout and build v8 source, because it will 
patch v8 SConstruct, or you could do it by manual

http://code.google.com/p/pyv8/wiki/HowToBuild#Runtime_Type_Information_and_C++_E
xception_in_v8_3.0

The boost version is not import, 1.40 or later will be ok
```

Original comment by `flier...@gmail.com` on 19 Mar 2011 at 9:29

**Comment by GoogleCodeExporter** [comment]
```
it already checked out and patched it itself (because i forgot to set v8_home).

the version of boost is not important but boost thought I have python2.6 
instead of 2.5 (I have both), how can I install boost:python for python2.5 ?

thanks for your help.
```

Original comment by `on.cel...@gmail.com` on 20 Mar 2011 at 11:03

**Comment by GoogleCodeExporter** [comment]
```
If you want to build boost with Python 2.5 by manual, I think you should set 
some environment variables.

You could check boost's document for more detail

http://www.boost.org/doc/libs/1_46_0/libs/python/doc/building.html
```

Original comment by `flier...@gmail.com` on 20 Mar 2011 at 5:48

**Comment by GoogleCodeExporter** [comment]
```
so, are there any feedback? I will close the issue
```

Original comment by `flier...@gmail.com` on 6 Apr 2011 at 4:53
- Changed state: **WontFix**

**Comment by GoogleCodeExporter** [comment]
```
Ok for the moment, if I reproduce I will let you know.
thanks.
```

Original comment by `on.cel...@gmail.com` on 7 Apr 2011 at 6:45

**Comment by GoogleCodeExporter** [comment]
```
thanks :)
```

Original comment by `flier...@gmail.com` on 8 Apr 2011 at 1:34
