### ISSUE TITLE
Install failed on Ubuntu 10.10 x86_64

### ISSUE THREAD

**Issue by GoogleCodeExporter** [charx0r/pyv8#82]
```
For a Ubuntu 10.10 x86_64 machine
1. svn checkout latest v8 and pyv8
2. built v8 - scons arch=x64
3. pyv8 install failed with msg

/usr/bin/ld: /home/nomind/lab/v8/trunk/libv8.a(allocation.o): relocation 
R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared 
object; recompile with -fPIC
/home/nomind/lab/v8/trunk/libv8.a: could not read symbols: Bad value
collect2: ld returned 1 exit status

4. built shared v8 - scons arch=x64 library=shared
5. pyv8 installed successfully but when did import PyV8 

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "PyV8.py", line 17, in <module>
    import _PyV8
ImportError: 
/usr/local/lib/python2.6/dist-packages/PyV8-1.0-py2.6-linux-x86_64.egg/_PyV8.so:
 undefined symbol: _ZTIN2v88internal9ZoneScopeE

6. removed AST.cpp from setup.py and installed again, got segmentation fault

Please, help me.
```

Original issue reported on code.google.com by `reachnom...@gmail.com` on 10 Apr 2011 at 1:55

**Comment by GoogleCodeExporter** [comment]
```
Please use `python setup.py build` to checkout and build v8, because pyv8 need 
to patch its SConstruct script; if you want to build v8 by manual, please check 
wiki for more detail.
```

Original comment by `flier...@gmail.com` on 10 Apr 2011 at 4:02
- Changed state: **WontFix**
- Added labels: **OpSys-Linux**

**Comment by GoogleCodeExporter** [comment]
```
Still could not fix the issue

1. ran python setup.py build
2. on import PyV8 got error

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "PyV8.py", line 17, in <module>
    import _PyV8
ImportError: 
/usr/local/lib/python2.6/dist-packages/PyV8-1.0-py2.6-linux-x86_64.egg/_PyV8.so:
 undefined symbol: 
_ZN2v88internal10AstVisitor17VisitDeclarationsEPNS0_8ZoneListIPNS0_11Declaration
EEE

3. Now, removed AST.cpp and intsalled again, got segmentation fault on import

```

Original comment by `reachnom...@gmail.com` on 10 Apr 2011 at 4:59

**Comment by GoogleCodeExporter** [comment]
```
Could you build v8 and pyv8 from clean source code? It seems your v8 has built 
without x64 mode and -fPIC. 

/usr/bin/ld: /home/nomind/lab/v8/trunk/libv8.a(allocation.o): relocation 
R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared 
object; recompile with -fPIC
```

Original comment by `flier...@gmail.com` on 11 Apr 2011 at 7:02
